import { motion } from "framer-motion";
import {
  FaCheckCircle,
  FaTimesCircle,
  FaThumbsUp,
  FaThumbsDown,
  FaChartBar,
} from "react-icons/fa";

function DecisionCard({ decision }) {
  if (!decision) return null;

  const isInvest = decision.recommendation?.toLowerCase() === "invest";
  const confidence = Number(decision.confidence) || 0;

  return (
    <motion.section
      initial={{ opacity: 0, y: 25 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.9 }}
      className="min-w-0 overflow-hidden rounded-[2rem] border border-slate-200/80 bg-white/90 p-7 shadow-[0_20px_60px_-25px_rgba(15,23,42,0.3)] backdrop-blur sm:p-8"
    >
      <div className="mb-8 flex items-center gap-3">
        <div className={`rounded-2xl p-3 ${isInvest ? "bg-emerald-100" : "bg-rose-100"}`}>
          {isInvest ? (
            <FaCheckCircle className="text-2xl text-emerald-600" />
          ) : (
            <FaTimesCircle className="text-2xl text-rose-600" />
          )}
        </div>

        <div>
          <h2 className="text-2xl font-bold text-slate-900">AI Recommendation</h2>
          <p className="text-sm text-slate-500">Final investment decision generated by AI</p>
        </div>
      </div>

      <div className="mb-8">
        <span className={`inline-flex items-center rounded-full px-6 py-3 font-semibold text-white shadow-lg ${isInvest ? "bg-emerald-600" : "bg-rose-600"}`}>
          {decision.recommendation}
        </span>
      </div>

      <div className="mb-8">
        <div className="mb-3 flex items-center gap-2">
          <FaChartBar className="text-blue-600" />
          <h3 className="text-lg font-semibold">Confidence Score</h3>
        </div>

        <div className="h-4 overflow-hidden rounded-full bg-slate-200">
          <div
            className={`h-full rounded-full ${isInvest ? "bg-emerald-600" : "bg-rose-600"}`}
            style={{ width: `${Math.min(Math.max(confidence, 0), 100)}%` }}
          />
        </div>

        <p className="mt-2 text-sm text-slate-600">{confidence}% Confidence</p>
      </div>

      <div className="grid gap-8 md:grid-cols-2">
        <div>
          <div className="mb-4 flex items-center gap-2">
            <FaThumbsUp className="text-emerald-600" />
            <h3 className="text-xl font-semibold">Pros</h3>
          </div>

          <ul className="space-y-3">
            {decision.pros?.map((item, index) => (
              <li key={index} className="rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-slate-700">
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <div className="mb-4 flex items-center gap-2">
            <FaThumbsDown className="text-rose-600" />
            <h3 className="text-xl font-semibold">Cons</h3>
          </div>

          <ul className="space-y-3">
            {decision.cons?.map((item, index) => (
              <li key={index} className="rounded-xl border border-rose-100 bg-rose-50 p-3 text-slate-700">
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mt-10 rounded-2xl border border-slate-200 bg-slate-50 p-5 leading-8 text-slate-700">
        <h3 className="mb-3 text-xl font-semibold text-slate-900">Summary</h3>
        <p>{decision.summary}</p>
      </div>
    </motion.section>
  );
}

export default DecisionCard;